name: Setup Next.js App

on:
  workflow_dispatch:

jobs:
  create-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create Next.js app
        run: |
          npx create-next-app@latest tempapp --typescript --eslint --tailwind --app --no-git --yes
          shopt -s dotglob
          cp -r tempapp/* .
          rm -rf tempapp

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Scaffold Next.js app"
          git push
